### ISSUE TITLE
undefined: oauth2.AuthorizeCodeGrantStorage

### ISSUE THREAD

**Issue by chinglinwen** [ory/fosite#206]
Hi,
I'm trying to run the hydra-consent-app-go
> although I may not run glide successfully( somewhat `Update failed for golang.org/x/sys: Cannot detect VCS`) , I don't see any mention of fostie on the glide.yaml file though.

However I use the following to test this issue
```
$ go run main1.go
# github.com/ory/hydra/pkg
..\hydra\pkg\fosite_storer.go:14: undefined: oauth2.AuthorizeCodeGrantStorage

$ cat main1.go
package main

import (
        "fmt"
        _ "github.com/ory/hydra/sdk"
)

func main() {
        fmt.Println("hello")
}

$ cd ../fosite/

wen@wen-PC MINGW64 /h/gocode/src/github.com/ory/fosite (master)
$ git log |head
commit fa50c80d36bbc8dda2633b59617689d8ef21042c
Author: akuma06 <demon.akuma06@gmail.com>
Date:   Sat Jul 29 10:02:28 2017 +0200

    docs: fixes documentation oauth2 variable and updates old method (#205)

$ cd ../hydra

$ git log
commit c94ba07f251af90e800e1d0fb50c0805ba473e75
Author: arekkas <aeneas@ory.am>
Date:   Tue Jul 11 13:01:31 2017 +0200

    docs: update readme

```

It seems it exist before, and now that file (flow_authorize_code_storage.go) is gone.

sourcegraph link: https://sourcegraph.com/github.com/ory/fosite@ef8f1757f0c26317fd7dbb46f66fde7516a3b4bb/-/blob/handler/oauth2/flow_authorize_code_storage.go#L8

```
$ go version
go version go1.8 windows/amd64
```

**Comment by arekkas** [comment]
This should be resolved now!

**Comment by chinglinwen** [comment]
I tested it, the issue still exist, the latest commit fa50c80  16 days ago which is before the issue is been created, I don't think it has resolved.

**Comment by arekkas** [comment]
The file was removed in fosite, not by accident, but by design. I updated the https://github.com/ory/hydra-consent-app-go repository to the latest fosite, which should resolve the issue you are describing. Can you try updating those dependencies?

Also, please use glide to install these things, as mentioned in the readme's ([fosite](https://github.com/ory/fosite#installation), [hydra](https://github.com/ory/hydra#building-from-source), and [consent app](https://github.com/ory/hydra-consent-app-go/blob/master/README.md#hydra-consent-app-go) :)

Hope this helps!

**Comment by chinglinwen** [comment]
Ah, I got it now, thanks. 

I actually tried glide install ( before I reply the tested result), it gives the following error. 

```
wen@hello:~$ cd $GOPATH/src/github.com/ory/hydra-consent-app-go
wen@hello:~/gocode/src/github.com/ory/hydra-consent-app-go$ glide install
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching github.com/asaskevich/govalidator
[INFO]  --> Fetching github.com/davecgh/go-spew
[INFO]  --> Fetching github.com/dgrijalva/jwt-go
[INFO]  --> Fetching github.com/fsnotify/fsnotify
[INFO]  --> Fetching github.com/go-sql-driver/mysql
[INFO]  --> Fetching github.com/golang/protobuf
[INFO]  --> Fetching github.com/gorilla/context
[INFO]  --> Fetching github.com/gorilla/mux
[INFO]  --> Fetching github.com/gorilla/securecookie
[INFO]  --> Fetching github.com/gorilla/sessions
[INFO]  --> Fetching github.com/hashicorp/golang-lru
[INFO]  --> Fetching github.com/hashicorp/hcl
[INFO]  --> Fetching github.com/imdario/mergo
[INFO]  --> Fetching github.com/inconshreveable/mousetrap
[INFO]  --> Fetching github.com/jehiah/go-strftime
[INFO]  --> Fetching github.com/jmoiron/sqlx
[INFO]  --> Fetching github.com/julienschmidt/httprouter
[INFO]  --> Fetching github.com/lib/pq
[INFO]  --> Fetching github.com/magiconair/properties
[INFO]  --> Fetching github.com/meatballhat/negroni-logrus
[INFO]  --> Fetching github.com/mitchellh/mapstructure
[INFO]  --> Fetching github.com/mohae/deepcopy
[INFO]  --> Fetching github.com/moul/http2curl
[INFO]  --> Fetching github.com/oleiade/reflections
[INFO]  --> Fetching github.com/ory/common
[INFO]  --> Fetching github.com/ory/fosite
[INFO]  --> Fetching github.com/ory/herodot
[INFO]  --> Fetching github.com/ory/hydra
[INFO]  --> Fetching github.com/ory/ladon
[INFO]  --> Fetching github.com/pborman/uuid
[INFO]  --> Fetching github.com/pelletier/go-toml
[INFO]  --> Fetching github.com/pkg/errors
[INFO]  --> Fetching github.com/pmezard/go-difflib
[INFO]  --> Fetching github.com/rubenv/sql-migrate
[INFO]  --> Fetching github.com/segmentio/analytics-go
[INFO]  --> Fetching github.com/segmentio/backo-go
[INFO]  --> Fetching github.com/sirupsen/logrus
[INFO]  --> Fetching github.com/spf13/afero
[INFO]  --> Fetching github.com/spf13/cast
[INFO]  --> Fetching github.com/spf13/cobra
[INFO]  --> Fetching github.com/spf13/jwalterweatherman
[INFO]  --> Fetching github.com/spf13/pflag
[INFO]  --> Fetching github.com/spf13/viper
[INFO]  --> Fetching github.com/square/go-jose
[INFO]  --> Fetching github.com/stretchr/testify
[INFO]  --> Fetching github.com/urfave/negroni
[INFO]  --> Fetching github.com/xtgo/uuid
[INFO]  --> Fetching golang.org/x/crypto
[INFO]  --> Fetching golang.org/x/net
[INFO]  --> Fetching golang.org/x/oauth2
[INFO]  --> Fetching golang.org/x/sys
[INFO]  --> Fetching golang.org/x/text
[INFO]  --> Fetching google.golang.org/appengine
[INFO]  --> Fetching gopkg.in/gorp.v1
[INFO]  --> Fetching gopkg.in/square/go-jose.v1
[INFO]  --> Fetching gopkg.in/yaml.v2
[INFO]  Setting references.
[INFO]  --> Setting version for github.com/davecgh/go-spew to 6d212800a42e8ab5c146b8ace3490ee17e5225f9.
[INFO]  --> Setting version for github.com/jmoiron/sqlx to d9bd385d68c068f1fabb5057e3dedcbcbb039d0f.
[INFO]  --> Setting version for github.com/asaskevich/govalidator to 4918b99a7cb949bb295f3c7bbaf24b577d806e35.
[INFO]  --> Setting version for github.com/inconshreveable/mousetrap to 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75.
[INFO]  --> Setting version for github.com/jehiah/go-strftime to 834e15c05a45371503440cc195bbd05c9a0968d9.
[INFO]  --> Setting version for github.com/gorilla/context to 1ea25387ff6f684839d82767c1733ff4d4d15d0a.
[INFO]  --> Setting version for github.com/hashicorp/hcl to 392dba7d905ed5d04a5794ba89f558b27e2ba1ca.
[INFO]  --> Setting version for github.com/dgrijalva/jwt-go to d2709f9f1f31ebcda9651b03077758c1f3a0018c.
[INFO]  --> Setting version for github.com/gorilla/sessions to ca9ada44574153444b00d3fd9c8559e4cc95f896.
[INFO]  --> Setting version for github.com/gorilla/mux to 392c28fe23e1c45ddba891b0320b3b5df220beea.
[INFO]  --> Setting version for github.com/go-sql-driver/mysql to a0583e0143b1624142adab07e0e97fe106d99561.
[INFO]  --> Setting version for github.com/golang/protobuf to 69b215d01a5606c843240eab4937eab3acee6530.
[INFO]  --> Setting version for github.com/meatballhat/negroni-logrus to 259659cbe5df2a5732a3c677d040058215be1ee7.
[INFO]  --> Setting version for github.com/hashicorp/golang-lru to 0a025b7e63adc15a622f29b0b2c4c3848243bbf6.
[INFO]  --> Setting version for github.com/gorilla/securecookie to e59506cc896acb7f7bf732d4fdf5e25f7ccd8983.
[INFO]  --> Setting version for github.com/julienschmidt/httprouter to 8c199fb6259ffc1af525cc3ad52ee60ba8359669.
[INFO]  --> Setting version for github.com/imdario/mergo to 3e95a51e0639b4cf372f2ccf74c86749d747fbdc.
[INFO]  --> Setting version for github.com/magiconair/properties to 51463bfca2576e06c62a8504b5c0f06d61312647.
[INFO]  --> Setting version for github.com/lib/pq to 8837942c3e09574accbc5f150e2c5e057189cace.
[INFO]  --> Setting version for github.com/fsnotify/fsnotify to 4da3e2cfbabc9f751898f250b49f2439785783a1.
[INFO]  --> Setting version for github.com/mitchellh/mapstructure to d0303fe809921458f417bcf828397a65db30a7e4.
[INFO]  --> Setting version for github.com/mohae/deepcopy to 491d3605edfb866af34a48075bd4355ac1bf46ca.
[INFO]  --> Setting version for github.com/moul/http2curl to 4e24498b31dba4683efb9d35c1c8a91e2eda28c8.
[INFO]  --> Setting version for github.com/oleiade/reflections to 2b6ec3da648e3e834dc41bad8d9ed7f2dc6a9496.
[INFO]  --> Setting version for github.com/ory/common to ba06ec2f738cb3a55608657c2e998a1eef675423.
[INFO]  --> Setting version for github.com/ory/fosite to ef8f1757f0c26317fd7dbb46f66fde7516a3b4bb.
[INFO]  --> Setting version for github.com/pelletier/go-toml to 69d355db5304c0f7f809a2edc054553e7142f016.
[INFO]  --> Setting version for github.com/pmezard/go-difflib to d8ed2627bdf02c080bf22230dbb337003b7aba2d.
[INFO]  --> Setting version for github.com/rubenv/sql-migrate to 72a5478faa469f9023cc1802367cddfc5270acbb.
[INFO]  --> Setting version for github.com/ory/herodot to 5bb399b8a5aa583343a2108e723b990432b4a1b4.
[INFO]  --> Setting version for github.com/segmentio/analytics-go to 2d840d861c322bdf5346ba7917af1c2285e653d3.
[INFO]  --> Setting version for github.com/ory/ladon to 80ec7e047ca2806a4491df41d5e9a2ad73b936a0.
[INFO]  --> Setting version for github.com/ory/hydra to 4651a2303a695ed79955ae64ec9fd7e5dc697906.
[INFO]  --> Setting version for github.com/pborman/uuid to a97ce2ca70fa5a848076093f05e639a89ca34d06.
[INFO]  --> Setting version for github.com/pkg/errors to 645ef00459ed84a119197bfb8d8205042c6df63d.
[INFO]  --> Setting version for github.com/segmentio/backo-go to 204274ad699c0983a70203a566887f17a717fef4.
[INFO]  --> Setting version for github.com/sirupsen/logrus to 181d419aa9e2223811b824e8f0b4af96f9ba9302.
[INFO]  --> Setting version for github.com/spf13/afero to 9be650865eab0c12963d8753212f4f9c66cdcf12.
[INFO]  --> Setting version for github.com/spf13/cast to acbeb36b902d72a7a4c18e8f3241075e7ab763e4.
[INFO]  --> Setting version for github.com/spf13/cobra to 8c6fa02d2225de0f9bdcb7ca912556f68d172d8c.
[INFO]  --> Setting version for github.com/spf13/jwalterweatherman to 0efa5202c04663c757d84f90f5219c1250baf94f.
[INFO]  --> Setting version for github.com/spf13/pflag to e57e3eeb33f795204c1ca35f56c44f83227c6e66.
[INFO]  --> Setting version for github.com/square/go-jose to aa2e30fdd1fe9dd3394119af66451ae790d50e0d.
[INFO]  --> Setting version for github.com/stretchr/testify to 69483b4bd14f5845b5a1e55bca19e954e827f1d0.
[INFO]  --> Setting version for github.com/spf13/viper to c1de95864d73a5465492829d7cb2dd422b19ac96.
[INFO]  --> Setting version for github.com/urfave/negroni to fde5e16d32adc7ad637e9cd9ad21d4ebc6192535.
[INFO]  --> Setting version for github.com/xtgo/uuid to a0b114877d4caeffbd7f87e3757c17fce570fea7.
[INFO]  --> Setting version for golang.org/x/crypto to 453249f01cfeb54c3d549ddb75ff152ca243f9d8.
[INFO]  --> Setting version for golang.org/x/oauth2 to b9780ec78894ab900c062d58ee3076cd9b2a4501.
[INFO]  --> Setting version for golang.org/x/net to dd2d9a67c97da0afa00d5726e28086007a0acce5.
[INFO]  --> Setting version for golang.org/x/sys to 6faef541c73732f438fb660a212750a9ba9f9362.
[INFO]  --> Setting version for golang.org/x/text to cfdf022e86b4ecfb646e1efbd7db175dd623a8fa.
[INFO]  --> Setting version for google.golang.org/appengine to 3a452f9e00122ead39586d68ffdb9c6e1326af3c.
[INFO]  --> Setting version for gopkg.in/square/go-jose.v1 to aa2e30fdd1fe9dd3394119af66451ae790d50e0d.
[INFO]  --> Setting version for gopkg.in/gorp.v1 to c87af80f3cc5036b55b83d77171e156791085e2e.
[INFO]  --> Setting version for gopkg.in/yaml.v2 to cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b.
[INFO]  Exporting resolved dependencies...
[INFO]  --> Exporting github.com/magiconair/properties
[INFO]  --> Exporting github.com/asaskevich/govalidator
[INFO]  --> Exporting github.com/julienschmidt/httprouter
[INFO]  --> Exporting github.com/jmoiron/sqlx
[INFO]  --> Exporting github.com/jehiah/go-strftime
[INFO]  --> Exporting github.com/inconshreveable/mousetrap
[INFO]  --> Exporting github.com/hashicorp/hcl
[INFO]  --> Exporting github.com/hashicorp/golang-lru
[INFO]  --> Exporting github.com/gorilla/sessions
[INFO]  --> Exporting github.com/gorilla/securecookie
[INFO]  --> Exporting github.com/gorilla/context
[INFO]  --> Exporting github.com/go-sql-driver/mysql
[INFO]  --> Exporting github.com/fsnotify/fsnotify
[INFO]  --> Exporting github.com/davecgh/go-spew
[INFO]  --> Exporting github.com/golang/protobuf
[INFO]  --> Exporting github.com/meatballhat/negroni-logrus
[INFO]  --> Exporting github.com/imdario/mergo
[INFO]  --> Exporting github.com/lib/pq
[INFO]  --> Exporting github.com/dgrijalva/jwt-go
[INFO]  --> Exporting github.com/gorilla/mux
[INFO]  --> Exporting github.com/mitchellh/mapstructure
[INFO]  --> Exporting github.com/oleiade/reflections
[INFO]  --> Exporting github.com/moul/http2curl
[INFO]  --> Exporting github.com/mohae/deepcopy
[INFO]  --> Exporting github.com/ory/common
[INFO]  --> Exporting github.com/pborman/uuid
[INFO]  --> Exporting github.com/pmezard/go-difflib
[INFO]  --> Exporting github.com/pkg/errors
[INFO]  --> Exporting github.com/pelletier/go-toml
[INFO]  --> Exporting github.com/segmentio/analytics-go
[INFO]  --> Exporting github.com/rubenv/sql-migrate
[INFO]  --> Exporting github.com/ory/herodot
[INFO]  --> Exporting github.com/ory/ladon
[INFO]  --> Exporting github.com/ory/fosite
[INFO]  --> Exporting github.com/ory/hydra
[INFO]  --> Exporting github.com/segmentio/backo-go
[INFO]  --> Exporting github.com/spf13/afero
[INFO]  --> Exporting github.com/sirupsen/logrus
[INFO]  --> Exporting github.com/spf13/cobra
[INFO]  --> Exporting github.com/spf13/cast
[INFO]  --> Exporting github.com/spf13/jwalterweatherman
[INFO]  --> Exporting github.com/spf13/pflag
[INFO]  --> Exporting github.com/spf13/viper
[INFO]  --> Exporting github.com/square/go-jose
[INFO]  --> Exporting github.com/stretchr/testify
[INFO]  --> Exporting github.com/xtgo/uuid
[INFO]  --> Exporting github.com/urfave/negroni
[INFO]  --> Exporting golang.org/x/crypto
[INFO]  --> Exporting golang.org/x/net
[INFO]  --> Exporting golang.org/x/oauth2
[INFO]  --> Exporting golang.org/x/sys
[INFO]  --> Exporting google.golang.org/appengine
[INFO]  --> Exporting golang.org/x/text
[INFO]  --> Exporting gopkg.in/gorp.v1
[INFO]  --> Exporting gopkg.in/square/go-jose.v1
[INFO]  --> Exporting gopkg.in/yaml.v2
[ERROR] Export failed for golang.org/x/sys: Unable to export source
[ERROR] Export failed for golang.org/x/net: Unable to export source
[ERROR] Export failed for golang.org/x/text: Unable to export source
[ERROR] Export failed for github.com/ory/hydra: Unable to export source
[ERROR] Unable to export dependencies to vendor directory: Unable to export source
Unable to export source
Unable to export source
Unable to export source
wen@hello:~/gocode/src/github.com/ory/hydra-consent-app-go$ 
```

Also, I'm good for closing this issue, I may later(don't know when) try it again when I got time (I'm doing something else now).
